# Multi-hole probe data (pressures, flow angles, etc).

float32 dp0		# flow probe diff. pressure 0
float32 dp1		# flow probe diff. pressure 1
float32 dp2		# flow probe diff. pressure 2
float32 dp3		# flow probe diff. pressure 3
float32 dp4		# flow probe diff. pressure 4
float32 dpS		# flow probe diff. pressure 5

float32 aoa		# angle of attack
float32 aos		# angle of sideslip

float32 tas		# true airspeed

uint32 id		# unique device ID for the sensor that does not change between power cycles
